version: "3.3"

services: 
  mongo:
    image: mongo
    restart: always
    ports:
      - 29017:27017
    networks: 
      - default-network

  api-backend:
    ports:
      - 8080:8080
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
    depends_on: 
      - mongo
    networks: 
      - default-network

networks: 
  default-network:
    driver: bridge