server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: Products
  data:
    mongodb:
      host: localhost
      port: 27017

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
